export type Recipe = {
  id: string
  name: string
  shortDescription: string
  mainIngredients: string[]
  fullIngredients: string[]
  preparationSteps: string[]
  healthBenefits: string[]
  image: string // food1, food2, food3, or food4
}

export const recipes: Recipe[] = [
  {
    id: "1",
    name: "Mediterranean Quinoa Bowl",
    shortDescription: "A nutritious bowl with quinoa, chickpeas, and fresh vegetables",
    mainIngredients: ["quinoa", "chickpeas", "cucumber", "tomato"],
    fullIngredients: [
      "1 cup quinoa",
      "1 can chickpeas, drained and rinsed",
      "1 large cucumber, diced",
      "2 medium tomatoes, diced",
      "1/4 cup red onion, finely chopped",
      "1/4 cup feta cheese, crumbled",
      "2 tbsp olive oil",
      "1 tbsp lemon juice",
      "Salt and pepper to taste",
      "Fresh herbs (parsley, mint)",
      "Garlic (minced)",
    ],
    preparationSteps: [
      "Cook quinoa according to package instructions and let cool",
      "Drain and rinse chickpeas, then pat dry",
      "Dice cucumber and tomatoes into bite-sized pieces",
      "Finely chop red onion and fresh herbs",
      "In a large bowl, combine quinoa, chickpeas, cucumber, tomatoes, and red onion",
      "Drizzle with olive oil and lemon juice",
      "Season with salt, pepper, and minced garlic",
      "Toss gently to combine",
      "Top with crumbled feta cheese and fresh herbs",
      "Serve immediately or refrigerate for up to 2 hours",
    ],
    healthBenefits: [
      "High in plant-based protein from quinoa and chickpeas",
      "Rich in fiber for digestive health",
      "Packed with antioxidants from fresh vegetables",
      "Provides essential vitamins and minerals",
      "Supports heart health with healthy fats",
    ],
    image: "food1",
  },
  {
    id: "2",
    name: "Berry Protein Smoothie",
    shortDescription: "A refreshing smoothie packed with protein and antioxidants",
    mainIngredients: ["berries", "greek yogurt", "honey"],
    fullIngredients: [
      "1 cup mixed berries (strawberries, blueberries, raspberries)",
      "1 cup Greek yogurt",
      "1 tbsp honey",
      "1/2 cup milk or almond milk",
      "1/2 banana (optional)",
      "1 tbsp chia seeds (optional)",
      "Ice cubes",
    ],
    preparationSteps: [
      "Wash and prepare fresh berries",
      "Add berries to a blender",
      "Add Greek yogurt and honey",
      "Pour in milk or almond milk",
      "Add optional banana and chia seeds if desired",
      "Add a handful of ice cubes",
      "Blend on high speed until smooth and creamy",
      "Pour into a glass and enjoy immediately",
    ],
    healthBenefits: [
      "High protein content from Greek yogurt",
      "Rich in antioxidants from berries",
      "Supports immune system function",
      "Provides natural energy boost",
      "Aids in muscle recovery and growth",
    ],
    image: "food2",
  },
  {
    id: "3",
    name: "Veggie Stir Fry",
    shortDescription: "A colorful mix of vegetables stir-fried to perfection",
    mainIngredients: ["bell peppers", "broccoli", "carrots", "tofu"],
    fullIngredients: [
      "2 bell peppers (red and yellow), sliced",
      "2 cups broccoli florets",
      "2 large carrots, julienned",
      "200g firm tofu, cubed",
      "2 tbsp soy sauce",
      "1 tbsp sesame oil",
      "1 tbsp vegetable oil",
      "2 cloves garlic, minced",
      "1 inch ginger, grated",
      "1 tbsp cornstarch (for tofu)",
      "Salt and pepper to taste",
      "Sesame seeds for garnish",
    ],
    preparationSteps: [
      "Press tofu to remove excess water, then cube and coat with cornstarch",
      "Heat vegetable oil in a large wok or pan over high heat",
      "Add tofu cubes and cook until golden brown, then set aside",
      "In the same pan, add sesame oil and heat",
      "Add minced garlic and grated ginger, stir for 30 seconds",
      "Add bell peppers and carrots, stir-fry for 2-3 minutes",
      "Add broccoli florets and continue cooking for 2-3 minutes",
      "Return tofu to the pan",
      "Pour in soy sauce and season with salt and pepper",
      "Stir everything together and cook for 1 more minute",
      "Garnish with sesame seeds and serve hot",
    ],
    healthBenefits: [
      "High in vitamins A and C from colorful vegetables",
      "Plant-based protein from tofu",
      "Low in calories and high in fiber",
      "Supports immune system",
      "Promotes healthy skin and vision",
    ],
    image: "food3",
  },
  {
    id: "4",
    name: "Avocado Toast Deluxe",
    shortDescription: "A healthy and satisfying breakfast with whole grain bread and fresh toppings",
    mainIngredients: ["avocado", "bread", "tomato"],
    fullIngredients: [
      "2 slices whole grain bread",
      "1 ripe avocado",
      "2-3 cherry tomatoes, sliced",
      "1/4 red onion, thinly sliced",
      "1 tbsp lemon juice",
      "Salt and pepper to taste",
      "Red pepper flakes (optional)",
      "Fresh herbs (cilantro or basil)",
      "Olive oil for drizzling",
    ],
    preparationSteps: [
      "Toast the whole grain bread until golden and crispy",
      "Cut avocado in half, remove pit, and scoop out flesh",
      "Mash avocado in a bowl with lemon juice, salt, and pepper",
      "Spread mashed avocado evenly on toasted bread",
      "Arrange sliced cherry tomatoes on top",
      "Add thinly sliced red onion",
      "Drizzle with a bit of olive oil",
      "Sprinkle with red pepper flakes if desired",
      "Garnish with fresh herbs",
      "Serve immediately",
    ],
    healthBenefits: [
      "Healthy monounsaturated fats from avocado",
      "High in fiber from whole grain bread",
      "Rich in potassium and folate",
      "Supports heart health",
      "Provides sustained energy",
    ],
    image: "food4",
  },
  {
    id: "5",
    name: "Chicken and Rice Bowl",
    shortDescription: "A protein-rich meal with tender chicken and fluffy rice",
    mainIngredients: ["chicken", "rice", "vegetables"],
    fullIngredients: [
      "2 chicken breasts, boneless and skinless",
      "1 cup brown or white rice",
      "1 cup mixed vegetables (peas, carrots, corn)",
      "2 tbsp olive oil",
      "2 cloves garlic, minced",
      "1 tsp paprika",
      "1 tsp cumin",
      "Salt and pepper to taste",
      "Fresh herbs for garnish",
      "Lemon wedges",
    ],
    preparationSteps: [
      "Cook rice according to package instructions",
      "Season chicken breasts with paprika, cumin, salt, and pepper",
      "Heat olive oil in a pan over medium-high heat",
      "Cook chicken breasts for 6-7 minutes per side until golden and cooked through",
      "Remove chicken and let rest, then slice",
      "In the same pan, add minced garlic and cook for 30 seconds",
      "Add mixed vegetables and cook until tender",
      "Fluff cooked rice and divide into bowls",
      "Top with sliced chicken and vegetables",
      "Garnish with fresh herbs and serve with lemon wedges",
    ],
    healthBenefits: [
      "High-quality protein from chicken",
      "Complex carbohydrates from rice for energy",
      "Balanced macronutrients",
      "Supports muscle growth and repair",
      "Provides essential B vitamins",
    ],
    image: "food1",
  },
  {
    id: "6",
    name: "Pasta Primavera",
    shortDescription: "Fresh pasta with seasonal vegetables in a light sauce",
    mainIngredients: ["pasta", "tomato", "bell peppers", "zucchini"],
    fullIngredients: [
      "200g pasta (penne or fusilli)",
      "2 medium tomatoes, diced",
      "1 bell pepper, sliced",
      "1 medium zucchini, sliced",
      "2 cloves garlic, minced",
      "2 tbsp olive oil",
      "1/4 cup vegetable broth",
      "Fresh basil leaves",
      "Parmesan cheese (optional)",
      "Salt and pepper to taste",
      "Red pepper flakes (optional)",
    ],
    preparationSteps: [
      "Cook pasta according to package instructions until al dente",
      "While pasta cooks, heat olive oil in a large pan",
      "Add minced garlic and cook until fragrant",
      "Add bell pepper and zucchini, cook for 3-4 minutes",
      "Add diced tomatoes and cook for 2 more minutes",
      "Pour in vegetable broth and bring to a simmer",
      "Drain pasta, reserving some pasta water",
      "Add pasta to the pan with vegetables",
      "Toss everything together, adding pasta water if needed",
      "Season with salt, pepper, and red pepper flakes",
      "Garnish with fresh basil and parmesan cheese",
      "Serve hot",
    ],
    healthBenefits: [
      "Rich in complex carbohydrates for energy",
      "High in fiber from vegetables",
      "Provides vitamins A and C",
      "Supports digestive health",
      "Low in saturated fat",
    ],
    image: "food2",
  },
  {
    id: "7",
    name: "Baked Potato with Toppings",
    shortDescription: "A hearty baked potato loaded with healthy toppings",
    mainIngredients: ["potato", "chicken", "broccoli", "cheese"],
    fullIngredients: [
      "2 large baking potatoes",
      "1 cup cooked chicken, shredded",
      "1 cup steamed broccoli florets",
      "1/4 cup shredded cheese (cheddar or mozzarella)",
      "2 tbsp Greek yogurt or sour cream",
      "2 tbsp chives, chopped",
      "Salt and pepper to taste",
      "Olive oil",
      "Butter (optional)",
    ],
    preparationSteps: [
      "Preheat oven to 400°F (200°C)",
      "Wash and dry potatoes, then pierce with a fork",
      "Rub potatoes with olive oil and sprinkle with salt",
      "Bake for 45-60 minutes until tender",
      "While potatoes bake, steam broccoli until tender",
      "Shred or dice cooked chicken",
      "Remove potatoes from oven and let cool slightly",
      "Cut a slit in the top of each potato",
      "Fluff the inside with a fork",
      "Top with shredded chicken, broccoli, and cheese",
      "Add a dollop of Greek yogurt",
      "Garnish with chives and serve hot",
    ],
    healthBenefits: [
      "High in potassium from potatoes",
      "Complete protein from chicken",
      "Rich in fiber and vitamins",
      "Supports bone health",
      "Provides sustained energy",
    ],
    image: "food3",
  },
  {
    id: "8",
    name: "Egg Scramble with Vegetables",
    shortDescription: "Protein-packed scrambled eggs with fresh vegetables",
    mainIngredients: ["eggs", "tomato", "bell peppers", "spinach"],
    fullIngredients: [
      "4 large eggs",
      "1 medium tomato, diced",
      "1/2 bell pepper, diced",
      "1 cup fresh spinach",
      "1/4 cup onion, diced",
      "1 tbsp butter or olive oil",
      "Salt and pepper to taste",
      "Fresh herbs (chives, parsley)",
      "Cheese (optional)",
    ],
    preparationSteps: [
      "Crack eggs into a bowl and whisk with salt and pepper",
      "Heat butter or olive oil in a non-stick pan over medium heat",
      "Add diced onion and bell pepper, cook for 2-3 minutes",
      "Add diced tomato and cook for 1 more minute",
      "Add fresh spinach and cook until wilted",
      "Pour in whisked eggs",
      "Gently scramble with a spatula",
      "Cook until eggs are set but still slightly creamy",
      "Add cheese if desired and let melt",
      "Garnish with fresh herbs and serve immediately",
    ],
    healthBenefits: [
      "High-quality protein from eggs",
      "Rich in vitamins A, C, and K",
      "Contains choline for brain health",
      "Supports muscle maintenance",
      "Provides essential amino acids",
    ],
    image: "food4",
  },
  {
    id: "9",
    name: "Rice and Bean Bowl",
    shortDescription: "A satisfying plant-based bowl with rice and protein-rich beans",
    mainIngredients: ["rice", "beans", "avocado", "tomato"],
    fullIngredients: [
      "1 cup brown rice",
      "1 can black beans, drained and rinsed",
      "1 ripe avocado, sliced",
      "1 medium tomato, diced",
      "1/4 cup corn (fresh or frozen)",
      "1/4 cup red onion, diced",
      "2 tbsp lime juice",
      "Fresh cilantro",
      "Salt and pepper to taste",
      "Hot sauce (optional)",
    ],
    preparationSteps: [
      "Cook brown rice according to package instructions",
      "While rice cooks, drain and rinse black beans",
      "Dice tomato and red onion",
      "Slice avocado",
      "Heat beans in a small pan or microwave until warm",
      "Fluff cooked rice and divide into bowls",
      "Top with warm black beans",
      "Add diced tomato, corn, and red onion",
      "Arrange avocado slices on top",
      "Drizzle with lime juice",
      "Garnish with fresh cilantro",
      "Add hot sauce if desired and serve",
    ],
    healthBenefits: [
      "Complete protein from rice and beans combination",
      "High in fiber for digestive health",
      "Rich in folate and iron",
      "Plant-based and cholesterol-free",
      "Supports heart health",
    ],
    image: "food1",
  },
  {
    id: "10",
    name: "Chicken Salad Wrap",
    shortDescription: "A light and fresh wrap with grilled chicken and vegetables",
    mainIngredients: ["chicken", "lettuce", "tomato", "avocado"],
    fullIngredients: [
      "2 chicken breasts, grilled and sliced",
      "2 large tortilla wraps",
      "2 cups mixed lettuce",
      "1 medium tomato, sliced",
      "1/2 avocado, sliced",
      "1/4 cup red onion, thinly sliced",
      "2 tbsp Greek yogurt or mayonnaise",
      "1 tbsp lemon juice",
      "Salt and pepper to taste",
      "Fresh herbs (dill, parsley)",
    ],
    preparationSteps: [
      "Season and grill chicken breasts until cooked through",
      "Let chicken rest, then slice into strips",
      "Mix Greek yogurt with lemon juice, salt, and pepper",
      "Warm tortilla wraps slightly",
      "Spread yogurt mixture on each wrap",
      "Layer with mixed lettuce",
      "Add sliced chicken strips",
      "Top with tomato slices, avocado, and red onion",
      "Sprinkle with fresh herbs",
      "Roll up tightly and cut in half",
      "Serve immediately",
    ],
    healthBenefits: [
      "Lean protein from chicken",
      "Healthy fats from avocado",
      "Low in carbohydrates",
      "High in vitamins and minerals",
      "Supports weight management",
    ],
    image: "food2",
  },
  {
    id: "11",
    name: "Vegetable Fried Rice",
    shortDescription: "A quick and healthy fried rice loaded with vegetables",
    mainIngredients: ["rice", "eggs", "carrots", "peas"],
    fullIngredients: [
      "2 cups cooked rice (preferably day-old)",
      "2 large eggs",
      "1 cup mixed vegetables (carrots, peas, corn)",
      "2 cloves garlic, minced",
      "2 tbsp soy sauce",
      "1 tbsp sesame oil",
      "2 tbsp vegetable oil",
      "2 green onions, chopped",
      "Salt and pepper to taste",
      "Sesame seeds (optional)",
    ],
    preparationSteps: [
      "Heat vegetable oil in a large wok or pan over high heat",
      "Scramble eggs in the pan, then remove and set aside",
      "Add minced garlic and cook for 30 seconds",
      "Add mixed vegetables and stir-fry for 2-3 minutes",
      "Add cooked rice and break up any clumps",
      "Stir-fry for 2-3 minutes until rice is heated through",
      "Return scrambled eggs to the pan",
      "Pour in soy sauce and sesame oil",
      "Toss everything together",
      "Add chopped green onions",
      "Season with salt and pepper",
      "Garnish with sesame seeds and serve hot",
    ],
    healthBenefits: [
      "Complete protein from eggs and rice",
      "High in fiber from vegetables",
      "Provides essential vitamins",
      "Quick and easy to prepare",
      "Supports energy levels",
    ],
    image: "food3",
  },
  {
    id: "12",
    name: "Avocado and Egg Toast",
    shortDescription: "A protein-rich breakfast combining eggs and avocado",
    mainIngredients: ["eggs", "avocado", "bread", "tomato"],
    fullIngredients: [
      "2 slices whole grain bread",
      "2 large eggs",
      "1 ripe avocado",
      "1 medium tomato, sliced",
      "1 tbsp lemon juice",
      "Salt and pepper to taste",
      "Red pepper flakes",
      "Fresh chives",
      "Butter or olive oil",
    ],
    preparationSteps: [
      "Toast bread until golden and crispy",
      "Mash avocado with lemon juice, salt, and pepper",
      "Heat butter or oil in a pan over medium heat",
      "Fry eggs to your preference (sunny-side up or over-easy)",
      "Spread mashed avocado on toast",
      "Top with fried eggs",
      "Add sliced tomato",
      "Season with salt, pepper, and red pepper flakes",
      "Garnish with fresh chives",
      "Serve immediately",
    ],
    healthBenefits: [
      "High-quality protein from eggs",
      "Healthy monounsaturated fats",
      "Rich in B vitamins",
      "Supports brain health",
      "Provides sustained energy",
    ],
    image: "food4",
  },
]

